//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chuong_Trinh_Quan_Ly_San_Xuat {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class lang_ja {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang_ja() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chuong_Trinh_Quan_Ly_San_Xuat.lang_ja", typeof(lang_ja).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        internal static string admin {
            get {
                return ResourceManager.GetString("admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     レポート    .
        /// </summary>
        internal static string baocao {
            get {
                return ResourceManager.GetString("baocao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 作業指示書.
        /// </summary>
        internal static string ctsx {
            get {
                return ResourceManager.GetString("ctsx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アイテム一覧.
        /// </summary>
        internal static string danhmuc {
            get {
                return ResourceManager.GetString("danhmuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   在庫  .
        /// </summary>
        internal static string kiemkho {
            get {
                return ResourceManager.GetString("kiemkho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     人事  .
        /// </summary>
        internal static string nhansu {
            get {
                return ResourceManager.GetString("nhansu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 納入―出荷.
        /// </summary>
        internal static string nhapxuat {
            get {
                return ResourceManager.GetString("nhapxuat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注文書.
        /// </summary>
        internal static string PO {
            get {
                return ResourceManager.GetString("PO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string string1 {
            get {
                return ResourceManager.GetString("string1", resourceCulture);
            }
        }
    }
}
